### ISSUE TITLE
why does this have the filestores as dependencies?

### ISSUE THREAD

**Issue by AdrianRossouw** [mcollina/seneca-import-csv#8]
While trying to improve build times on a project I realized that it was installing a bunch of native mongo related modules, when the project doesn't even use mongo.

**Comment by mcollina** [comment]
Big question, I think I copied the project structure from somewhere else, and I forgot.
The only one needed is the json filestore, which should be moved in `devDependencies`.
Would you mind to send a PR?

**Comment by AdrianRossouw** [comment]
np. will do.

**Comment by AdrianRossouw** [comment]
done.
